package fluks.timerng;

import fluks.swing.utils.SwingUtils;
import fluks.timerng.Global.Sound;
import fluks.timerng.Settings.ActiveTab;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTabbedPane;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 */
public class GUI extends JFrame {
    private final Sound sound;
    private final TimerTab timerTab;
    private final AlarmTab alarmTab;
    private final StopwatchTab stopwatchTab;
    private final TimezonesTab timezonesTab;
    private static final String ICON_FILE = "/resources/icon.png";

    /**
     */
    public GUI() {
        initComponents();

        timerTab = new TimerTab();
        alarmTab = new AlarmTab();
        stopwatchTab = new StopwatchTab();
        timezonesTab = new TimezonesTab();
        tabbedPane.addTab("Timer", timerTab);
        tabbedPane.addTab("Alarm", alarmTab);
        tabbedPane.addTab("Stopwatch", stopwatchTab);
        tabbedPane.addTab("Timezones", timezonesTab);

        URL iconURL = getClass().getResource(ICON_FILE);
        this.setIconImage(new ImageIcon(iconURL).getImage());
        this.setTitle(Global.PROGRAM_NAME);
        setLocation(SwingUtils.getScreenCenterForWindow((Window) this));
        sound = Global.getSoundInstance();

        Global.Resolution r = Settings.INSTANCE.getResolution();
        if (r != null) {
            setSize(r.width(), r.height());
        }

        activateTab();
        notificationMenuItem.setState(Settings.INSTANCE.getNotify());
    }

    /**
     * 
     */
    private void activateTab() {
        var tab = Settings.INSTANCE.getActiveTab();
        for (Component c : tabbedPane.getComponents()) {
            var t = (Tab) c;
            if (t.getTab().equals(tab)) {
                tabbedPane.setSelectedComponent(c);
                return;
            }
        }
    }

    /**
     * @return 
     */
    private ActiveTab getActiveTab() {
        var c = tabbedPane.getSelectedComponent();
        var t =  ((Tab) c).getTab();
        return t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new JTabbedPane();
        jMenuBar1 = new JMenuBar();
        fileMenu = new JMenu();
        notificationMenuItem = new JCheckBoxMenuItem();
        jSeparator1 = new JPopupMenu.Separator();
        quitMenuItem = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(500, 400));
        setSize(new Dimension(100, 100));
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tabbedPane.setName(""); // NOI18N
        getContentPane().add(tabbedPane, BorderLayout.CENTER);
        tabbedPane.getAccessibleContext().setAccessibleName("");
        tabbedPane.getAccessibleContext().setAccessibleDescription("");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        notificationMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N, InputEvent.CTRL_DOWN_MASK));
        notificationMenuItem.setMnemonic('n');
        notificationMenuItem.setText("Show Notification");
        notificationMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                notificationMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(notificationMenuItem);
        fileMenu.add(jSeparator1);

        quitMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_Q, InputEvent.CTRL_DOWN_MASK));
        quitMenuItem.setMnemonic('q');
        quitMenuItem.setText("Quit");
        quitMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                quitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(quitMenuItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param evt 
     */
    private void quitMenuItemActionPerformed(ActionEvent evt) {//GEN-FIRST:event_quitMenuItemActionPerformed
        sound.getAlarm().closeClip();
        sound.getBeep().closeClip();

        Dimension d = getSize();
        Settings.INSTANCE.setResolution(d.width, d.height);
        timerTab.saveState();
        alarmTab.saveState();
        stopwatchTab.saveState();
        timezonesTab.saveState();
        Settings.INSTANCE.setActiveTab(getActiveTab());

        Settings.INSTANCE.flush();

        System.exit(0);
    }//GEN-LAST:event_quitMenuItemActionPerformed

    /**
     * @param evt 
     */
    private void notificationMenuItemActionPerformed(ActionEvent evt) {//GEN-FIRST:event_notificationMenuItemActionPerformed
        Settings.INSTANCE.setNotify(notificationMenuItem.getState());
    }//GEN-LAST:event_notificationMenuItemActionPerformed

    /**
     * @param evt 
     */
    private void formWindowClosing(WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        quitMenuItemActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args 
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize FlatLaf\n" + ex);
        }
        /* Create and display the form */
        SwingUtilities.invokeLater(() -> {
            var gui = new GUI();
            gui.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JMenu fileMenu;
    private JMenuBar jMenuBar1;
    private JPopupMenu.Separator jSeparator1;
    private JCheckBoxMenuItem notificationMenuItem;
    private JMenuItem quitMenuItem;
    private JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}