/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fluks.timerng;

/**
 *
 * @author jukka
 */
public class AlarmTab extends javax.swing.JPanel {

    /**
     * Creates new form TimerTab
     */
    public AlarmTab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        volumeLabel = new javax.swing.JLabel();
        volumeSlider = new javax.swing.JSlider();
        muteCheckBox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        hoursLabel = new javax.swing.JLabel();
        hoursSpinner = new javax.swing.JSpinner();
        minutesLabel = new javax.swing.JLabel();
        minutesSpinner = new javax.swing.JSpinner();
        secondsLabel = new javax.swing.JLabel();
        secondsSpinner = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        startStopButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        volumeLabel.setDisplayedMnemonic('v');
        volumeLabel.setLabelFor(volumeSlider);
        volumeLabel.setText("Volume");
        volumeLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));
        jPanel1.add(volumeLabel);

        volumeSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jPanel1.add(volumeSlider);

        muteCheckBox.setMnemonic('m');
        muteCheckBox.setText("Mute");
        jPanel1.add(muteCheckBox);

        add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        timeLabel.setFont(new java.awt.Font("Dialog", 1, 70)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("00:00:00");
        timeLabel.setAlignmentX(0.5F);
        timeLabel.setMaximumSize(new java.awt.Dimension(39999, 420));
        timeLabel.setPreferredSize(new java.awt.Dimension(42000, 96));
        jPanel2.add(timeLabel);

        jPanel3.setMinimumSize(new java.awt.Dimension(67, 32));
        jPanel3.setPreferredSize(new java.awt.Dimension(420, 44));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        hoursLabel.setDisplayedMnemonic('h');
        hoursLabel.setLabelFor(hoursSpinner);
        hoursLabel.setText("Hours");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(hoursLabel, gridBagConstraints);

        hoursSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(hoursSpinner, gridBagConstraints);

        minutesLabel.setDisplayedMnemonic('m');
        minutesLabel.setLabelFor(minutesSpinner);
        minutesLabel.setText("Minutes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(minutesLabel, gridBagConstraints);

        minutesSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(minutesSpinner, gridBagConstraints);

        secondsLabel.setDisplayedMnemonic('e');
        secondsLabel.setLabelFor(secondsSpinner);
        secondsLabel.setText("Seconds");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(secondsLabel, gridBagConstraints);

        secondsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(secondsSpinner, gridBagConstraints);

        jPanel2.add(jPanel3);

        startStopButton.setMnemonic('s');
        startStopButton.setText("Start / Stop");
        jPanel4.add(startStopButton);

        resetButton.setMnemonic('r');
        resetButton.setText("Reset");
        resetButton.setToolTipText("");
        jPanel4.add(resetButton);

        jPanel2.add(jPanel4);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hoursLabel;
    private javax.swing.JSpinner hoursSpinner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel minutesLabel;
    private javax.swing.JSpinner minutesSpinner;
    private javax.swing.JCheckBox muteCheckBox;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel secondsLabel;
    private javax.swing.JSpinner secondsSpinner;
    private javax.swing.JButton startStopButton;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables
}
