package fluks.timerng;

import fluks.swing.utils.SwingUtils;
import fluks.timerng.Settings.ActiveTab;
import fluks.timerng.sound.AbstractClipWrapper;
import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ContainerAdapter;
import java.awt.event.ContainerEvent;
import java.net.MalformedURLException;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 * 
 */
public class AlarmTab extends JPanel implements Tab {
    private LocalDateTime targetTime;
    private Timer timer;
    private AbstractClipWrapper alarm;
    private boolean muted;
    private final ActiveTab tab = Settings.ActiveTab.ALARM_TAB;

    /**
     */
    public AlarmTab() {
        initComponents();
        infoPanel.setVisible(false);

        alarm = Global.getSoundInstance().getAlarm();
        targetTime = LocalDateTime.now().withHour(0).withMinute(0).withSecond(0);

        getState();
    }

    /**
     * @return 
     */
    @Override
    public ActiveTab getTab() {
        return tab;
    }

    /**
     */
    public void saveState() {
        Settings.INSTANCE.setAlarmTabVolume(volumeSlider.getValue());
        Settings.INSTANCE.setAlarmTabMute(muted);
        var time = new TimeUnits(
            (int) hoursSpinner.getValue(),
            (int) minutesSpinner.getValue(),
            (int) secondsSpinner.getValue(),
            0
        );
        Settings.INSTANCE.setAlarmTabTimer(time);
    }

    /**
     */
    private void getState() {
        volumeSlider.setValue(Settings.INSTANCE.getAlarmTabVolume());

        muted = Settings.INSTANCE.getAlarmTabMute();
        muteCheckBox.setSelected(muted);
        alarm.mute(muted);

        var time = Settings.INSTANCE.getAlarmTabTimer();
        hoursSpinner.setValue(time.getHours());
        minutesSpinner.setValue(time.getMinutes());
        secondsSpinner.setValue(time.getSeconds());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        jPanel1 = new JPanel();
        volumeLabel = new JLabel();
        volumeSlider = new JSlider();
        muteCheckBox = new JCheckBox();
        jPanel2 = new JPanel();
        jPanel3 = new JPanel();
        hoursLabel = new JLabel();
        hoursSpinner = new JSpinner();
        minutesLabel = new JLabel();
        minutesSpinner = new JSpinner();
        secondsLabel = new JLabel();
        secondsSpinner = new JSpinner();
        infoPanel = new JPanel();
        remainingLabel = new JLabel();
        timeRemainingLabel = new JLabel();
        jPanel4 = new JPanel();
        startStopButton = new JButton();
        resetButton = new JButton();

        setBorder(BorderFactory.createEmptyBorder(20, 1, 20, 1));
        setLayout(new BoxLayout(this, BoxLayout.X_AXIS));

        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));

        volumeLabel.setDisplayedMnemonic('v');
        volumeLabel.setLabelFor(volumeSlider);
        volumeLabel.setText("Volume");
        volumeLabel.setBorder(BorderFactory.createEmptyBorder(1, 1, 20, 1));
        jPanel1.add(volumeLabel);

        volumeSlider.setOrientation(JSlider.VERTICAL);
        volumeSlider.setMaximumSize(new Dimension(32767, 32767));
        volumeSlider.addContainerListener(new ContainerAdapter() {
            public void componentAdded(ContainerEvent evt) {
                volumeSliderComponentAdded(evt);
            }
        });
        volumeSlider.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                volumeSliderStateChanged(evt);
            }
        });
        jPanel1.add(volumeSlider);

        muteCheckBox.setMnemonic('u');
        muteCheckBox.setText("Mute");
        muteCheckBox.addContainerListener(new ContainerAdapter() {
            public void componentAdded(ContainerEvent evt) {
                muteCheckBoxComponentAdded(evt);
            }
        });
        muteCheckBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                muteCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(muteCheckBox);

        add(jPanel1);

        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.PAGE_AXIS));

        jPanel3.setMinimumSize(new Dimension(67, 32));
        jPanel3.setPreferredSize(new Dimension(420, 44));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new GridBagLayout());

        hoursLabel.setDisplayedMnemonic('h');
        hoursLabel.setLabelFor(hoursSpinner);
        hoursLabel.setText("Hours");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        jPanel3.add(hoursLabel, gridBagConstraints);

        hoursSpinner.setModel(new SpinnerNumberModel(0, 0, 23, 1));
        hoursSpinner.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                hoursSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        jPanel3.add(hoursSpinner, gridBagConstraints);

        minutesLabel.setDisplayedMnemonic('m');
        minutesLabel.setLabelFor(minutesSpinner);
        minutesLabel.setText("Minutes");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        jPanel3.add(minutesLabel, gridBagConstraints);

        minutesSpinner.setModel(new SpinnerNumberModel(0, 0, 59, 1));
        minutesSpinner.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                minutesSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        jPanel3.add(minutesSpinner, gridBagConstraints);

        secondsLabel.setDisplayedMnemonic('e');
        secondsLabel.setLabelFor(secondsSpinner);
        secondsLabel.setText("Seconds");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        jPanel3.add(secondsLabel, gridBagConstraints);

        secondsSpinner.setModel(new SpinnerNumberModel(0, 0, 59, 1));
        secondsSpinner.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                secondsSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        jPanel3.add(secondsSpinner, gridBagConstraints);

        jPanel2.add(jPanel3);

        remainingLabel.setText("Remaining");
        infoPanel.add(remainingLabel);
        infoPanel.add(timeRemainingLabel);

        jPanel2.add(infoPanel);

        startStopButton.setMnemonic('s');
        startStopButton.setText("Start / Stop");
        startStopButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                startStopButtonActionPerformed(evt);
            }
        });
        jPanel4.add(startStopButton);

        resetButton.setMnemonic('r');
        resetButton.setText("Reset");
        resetButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel4.add(resetButton);

        jPanel2.add(jPanel4);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param evt 
     */
    private void volumeSliderStateChanged(ChangeEvent evt) {//GEN-FIRST:event_volumeSliderStateChanged
        int volume = volumeSlider.getValue();
        alarm.setVolume(volume, SwingUtils.getSliderRange(volumeSlider));
    }//GEN-LAST:event_volumeSliderStateChanged

    /**
     * @param evt 
     */
    private void muteCheckBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_muteCheckBoxActionPerformed
        muted = muteCheckBox.isSelected();
        alarm.mute(muted);
    }//GEN-LAST:event_muteCheckBoxActionPerformed

    /**
     * @param evt 
     */
    private void startStopButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_startStopButtonActionPerformed
        if (timer == null) {
            alarm.stopAndRewind();
            var currentTime = LocalDateTime.now();
            if (targetTime.isBefore(currentTime)) {
                targetTime = targetTime.plusDays(1);
            }
            infoPanel.setVisible(true);
            timer = new Timer();
            timer.scheduleAtFixedRate(new TimerTask() {
                @Override
                public void run() {
                    var now = LocalDateTime.now();
                    var diff = Duration.between(now, targetTime);
                    if (diff.toMillis() < 1000) {
                        SwingUtilities.invokeLater(() -> {
                            timeRemainingLabel.setText("00:00:00");
                        });
                        alarm.play();
                        timer.cancel();
                        timer = null;
                        if (Settings.INSTANCE.getNotify()) {
                            try {
                                // Set nano to 0 to not show it.
                                var time = targetTime.withNano(0).format(DateTimeFormatter.ISO_TIME);
                                SwingUtils.showDesktopNotification(
                                        "Alarm finished",
                                        "Alarm you set to " + time + " is finished.",
                                        Global.PROGRAM_NAME,
                                        null,
                                        5000);
                            }
                            catch (MalformedURLException | AWTException ex) {
                            }
                        }
                    }
                    else {
                        var remaining = String.format("%02d:%02d:%02d",
                            diff.toHoursPart(), diff.toMinutesPart(), diff.toSecondsPart());
                        SwingUtilities.invokeLater(() -> {
                            timeRemainingLabel.setText(remaining);
                        });
                    }
                }
            }, 0, 1000);
        }
        else {
            timer.cancel();
            timer = null;
        }
    }//GEN-LAST:event_startStopButtonActionPerformed

    /**
     * @param evt 
     */
    private void resetButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        hoursSpinner.setValue(0);
        minutesSpinner.setValue(0);
        secondsSpinner.setValue(0);
        timeRemainingLabel.setText("");
        infoPanel.setVisible(false);
        alarm.stopAndRewind();
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param evt 
     */
    private void hoursSpinnerStateChanged(ChangeEvent evt) {//GEN-FIRST:event_hoursSpinnerStateChanged
        targetTime = targetTime.withHour((int) hoursSpinner.getValue());
    }//GEN-LAST:event_hoursSpinnerStateChanged

    /**
     * @param evt 
     */
    private void minutesSpinnerStateChanged(ChangeEvent evt) {//GEN-FIRST:event_minutesSpinnerStateChanged
        targetTime = targetTime.withMinute((int) minutesSpinner.getValue());
    }//GEN-LAST:event_minutesSpinnerStateChanged

    /**
     * @param evt 
     */
    private void secondsSpinnerStateChanged(ChangeEvent evt) {//GEN-FIRST:event_secondsSpinnerStateChanged
        targetTime = targetTime.withSecond((int) secondsSpinner.getValue());
    }//GEN-LAST:event_secondsSpinnerStateChanged

    /**
     * @param evt 
     */
    private void volumeSliderComponentAdded(ContainerEvent evt) {//GEN-FIRST:event_volumeSliderComponentAdded
        int volume = Settings.INSTANCE.getAlarmTabVolume();
        volumeSlider.setValue(volume);
        alarm.setVolume(volume, SwingUtils.getSliderRange(volumeSlider));
    }//GEN-LAST:event_volumeSliderComponentAdded

    /**
     * @param evt 
     */
    private void muteCheckBoxComponentAdded(ContainerEvent evt) {//GEN-FIRST:event_muteCheckBoxComponentAdded
        muted = Settings.INSTANCE.getAlarmTabMute();
        alarm.mute(muted);
        muteCheckBox.setSelected(muted);
    }//GEN-LAST:event_muteCheckBoxComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel hoursLabel;
    private JSpinner hoursSpinner;
    private JPanel infoPanel;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JLabel minutesLabel;
    private JSpinner minutesSpinner;
    private JCheckBox muteCheckBox;
    private JLabel remainingLabel;
    private JButton resetButton;
    private JLabel secondsLabel;
    private JSpinner secondsSpinner;
    private JButton startStopButton;
    private JLabel timeRemainingLabel;
    private JLabel volumeLabel;
    private JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables
}
