package fluks.timerng;

import fluks.timerng.sound.NoSound;
import fluks.timerng.sound.Beep;
import fluks.timerng.sound.AbstractClipWrapper;
import fluks.timerng.sound.Alarm;
import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.awt.Window;
import java.io.InputStream;
import java.net.URL;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.SwingUtilities;
import javax.swing.JPanel;

public class GUI extends javax.swing.JFrame {
    final private TimeUnits time = new TimeUnits();
    final private TimeUnits targetTime = new TimeUnits();
    private Timer timer;
    private Timer timeLabelFlashTimer = null;
    private final Color timeLabelFg;
    private boolean timerIsRunning = false;
    private AbstractClipWrapper beep = new Beep();
    private AbstractClipWrapper alarm = new Alarm();
    private static final String BEEP_FILE = "/resources/beep.wav";
    private static final String ALARM_FILE = "/resources/alarm.wav";
    private static final String ICON_FILE = "/resources/icon.png";
    private static final String PROGRAM_NAME = "Timer-ng";

    public GUI() {
        initComponents();
        jTabbedPane1.addTab("Timer2", new TimerTab());
        jTabbedPane1.addTab("Alarm2", new AlarmTab());
        jTabbedPane1.addTab("Stopwatch2", new StopwatchTab());
        jTabbedPane1.addTab("TimezonesTab", new TimezonesTab());
        URL iconURL = getClass().getResource(ICON_FILE);
        this.setIconImage(new ImageIcon(iconURL).getImage());
        this.setTitle(PROGRAM_NAME);
        intervalCheckbox.setEnabled(false);
        setLocation(getScreenCenterForWindow((Window) this));
        getRootPane().setDefaultButton(startStopButton);
        timeLabelFg = timeLabel.getForeground();

        beep = loadSound(beep, BEEP_FILE);
        alarm = loadSound(alarm, ALARM_FILE);

        if ((beep instanceof NoSound) && (alarm instanceof NoSound)) {
            volumeSlider.setEnabled(false);
            muteCheckbox.setEnabled(false);
        }

        alarm.setVolume(getSliderMiddle(volumeSlider),
            getSlideRange(volumeSlider));
        beep.setVolume(getSliderMiddle(volumeSlider),
            getSlideRange(volumeSlider));
    }

    /** Load a sound object by opening a clip for it.
     * @param cw An object, which clip will be opened.
     * @param resource A path to resource. cw opens a clip to this resource.
     * @return An object, which clip is opened to the resource, or if something
     * fails, a {@link fi.fluks.NoSound NoSound} instance, which doesn't do
     * anything.
     */
    private AbstractClipWrapper loadSound(AbstractClipWrapper cw,
        String resource) {
        try (InputStream is = getClass().getResourceAsStream(resource)) {
            if (is == null)
                throw new Exception("Can't get system resource, " + resource);
            cw.openClip(is);
        }
        catch (Exception e) {
            cw.closeClip();
            JOptionPane.showMessageDialog(this,
                "Failed to load audio.\n\n" + e.getMessage());
            cw = new NoSound();
        }

        return cw;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TimerPanel = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        intervalCheckbox = new javax.swing.JCheckBox();
        TimePickerPanel = new javax.swing.JPanel();
        millisecondSpinner = new javax.swing.JSpinner();
        minuteSpinner = new javax.swing.JSpinner();
        hourSpinner = new javax.swing.JSpinner();
        secondSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        VolumePanel = new javax.swing.JPanel();
        volumeLabel = new javax.swing.JLabel();
        volumeSlider = new javax.swing.JSlider();
        muteCheckbox = new javax.swing.JCheckBox();
        ButtonPanel = new javax.swing.JPanel();
        startStopButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        AlarmPanel = new javax.swing.JPanel();
        VolumePanel1 = new javax.swing.JPanel();
        volumeLabel1 = new javax.swing.JLabel();
        volumeSlider1 = new javax.swing.JSlider();
        muteCheckbox1 = new javax.swing.JCheckBox();
        CurrentTimeLabel = new javax.swing.JLabel();
        ButtonPanel1 = new javax.swing.JPanel();
        startStopButton1 = new javax.swing.JButton();
        resetButton1 = new javax.swing.JButton();
        TimePickerPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        HourSelectorSpinner = new javax.swing.JSpinner();
        MinuteSelectorSpinner = new javax.swing.JSpinner();
        SecondSelectorSpinner = new javax.swing.JSpinner();
        StopwatchPanel = new javax.swing.JPanel();
        VolumePanel2 = new javax.swing.JPanel();
        volumeLabel2 = new javax.swing.JLabel();
        volumeSlider2 = new javax.swing.JSlider();
        muteCheckbox2 = new javax.swing.JCheckBox();
        CurrentTimeLabel1 = new javax.swing.JLabel();
        ButtonPanel2 = new javax.swing.JPanel();
        startStopButton2 = new javax.swing.JButton();
        resetButton2 = new javax.swing.JButton();
        LapButton = new javax.swing.JButton();
        LapPane = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        quitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setName(""); // NOI18N

        timeLabel.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("00:00:00:000");

        intervalCheckbox.setMnemonic('i');
        intervalCheckbox.setText("Interval");
        intervalCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intervalCheckboxActionPerformed(evt);
            }
        });

        millisecondSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        millisecondSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                millisecondSpinnerStateChanged(evt);
            }
        });

        minuteSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        minuteSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                minuteSpinnerStateChanged(evt);
            }
        });

        hourSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        hourSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hourSpinnerStateChanged(evt);
            }
        });

        secondSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        secondSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                secondSpinnerStateChanged(evt);
            }
        });

        jLabel1.setDisplayedMnemonic('h');
        jLabel1.setLabelFor(hourSpinner);
        jLabel1.setText("hours");

        jLabel2.setDisplayedMnemonic('n');
        jLabel2.setLabelFor(minuteSpinner);
        jLabel2.setText("minutes");

        jLabel3.setDisplayedMnemonic('e');
        jLabel3.setLabelFor(secondSpinner);
        jLabel3.setText("seconds");

        jLabel4.setDisplayedMnemonic('l');
        jLabel4.setLabelFor(millisecondSpinner);
        jLabel4.setText("milliseconds");

        javax.swing.GroupLayout TimePickerPanelLayout = new javax.swing.GroupLayout(TimePickerPanel);
        TimePickerPanel.setLayout(TimePickerPanelLayout);
        TimePickerPanelLayout.setHorizontalGroup(
            TimePickerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimePickerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TimePickerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hourSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TimePickerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minuteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TimePickerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TimePickerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(millisecondSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TimePickerPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {hourSpinner, millisecondSpinner, minuteSpinner, secondSpinner});

        TimePickerPanelLayout.setVerticalGroup(
            TimePickerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimePickerPanelLayout.createSequentialGroup()
                .addGroup(TimePickerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TimePickerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(hourSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(millisecondSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        TimePickerPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {hourSpinner, millisecondSpinner, minuteSpinner, secondSpinner});

        volumeLabel.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        volumeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volumeLabel.setLabelFor(volumeSlider);
        volumeLabel.setText("Volume");
        volumeLabel.setToolTipText("");
        volumeLabel.setAlignmentX(0.5F);

        volumeSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSliderStateChanged(evt);
            }
        });

        muteCheckbox.setMnemonic('m');
        muteCheckbox.setText("Mute");
        muteCheckbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        muteCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muteCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VolumePanelLayout = new javax.swing.GroupLayout(VolumePanel);
        VolumePanel.setLayout(VolumePanelLayout);
        VolumePanelLayout.setHorizontalGroup(
            VolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolumePanelLayout.createSequentialGroup()
                .addGroup(VolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volumeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VolumePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(VolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(volumeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(muteCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                .addContainerGap())
        );
        VolumePanelLayout.setVerticalGroup(
            VolumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolumePanelLayout.createSequentialGroup()
                .addComponent(volumeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(muteCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        startStopButton.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        startStopButton.setMnemonic('s');
        startStopButton.setText("Start/Stop");
        startStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStopButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        resetButton.setMnemonic('r');
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(startStopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startStopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TimerPanelLayout = new javax.swing.GroupLayout(TimerPanel);
        TimerPanel.setLayout(TimerPanelLayout);
        TimerPanelLayout.setHorizontalGroup(
            TimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimerPanelLayout.createSequentialGroup()
                .addComponent(VolumePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimePickerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TimerPanelLayout.createSequentialGroup()
                        .addGroup(TimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(intervalCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        TimerPanelLayout.setVerticalGroup(
            TimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimerPanelLayout.createSequentialGroup()
                .addGroup(TimerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TimerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VolumePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TimerPanelLayout.createSequentialGroup()
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intervalCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimePickerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Timer", TimerPanel);

        volumeLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        volumeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volumeLabel1.setLabelFor(volumeSlider);
        volumeLabel1.setText("Volume");
        volumeLabel1.setToolTipText("");
        volumeLabel1.setAlignmentX(0.5F);

        volumeSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSlider1StateChanged(evt);
            }
        });

        muteCheckbox1.setMnemonic('m');
        muteCheckbox1.setText("Mute");
        muteCheckbox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        muteCheckbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muteCheckbox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VolumePanel1Layout = new javax.swing.GroupLayout(VolumePanel1);
        VolumePanel1.setLayout(VolumePanel1Layout);
        VolumePanel1Layout.setHorizontalGroup(
            VolumePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolumePanel1Layout.createSequentialGroup()
                .addGroup(VolumePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volumeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VolumePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(VolumePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(volumeSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(muteCheckbox1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                .addContainerGap())
        );
        VolumePanel1Layout.setVerticalGroup(
            VolumePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolumePanel1Layout.createSequentialGroup()
                .addComponent(volumeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(muteCheckbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CurrentTimeLabel.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        CurrentTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CurrentTimeLabel.setText("00:00:00");
        CurrentTimeLabel.setToolTipText("");

        startStopButton1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        startStopButton1.setMnemonic('s');
        startStopButton1.setText("Start/Stop");
        startStopButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStopButton1ActionPerformed(evt);
            }
        });

        resetButton1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        resetButton1.setMnemonic('r');
        resetButton1.setText("Reset");
        resetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanel1Layout = new javax.swing.GroupLayout(ButtonPanel1);
        ButtonPanel1.setLayout(ButtonPanel1Layout);
        ButtonPanel1Layout.setHorizontalGroup(
            ButtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(startStopButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(resetButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        ButtonPanel1Layout.setVerticalGroup(
            ButtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ButtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startStopButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        TimePickerPanel1.setLayout(new java.awt.GridLayout(2, 3));

        jLabel5.setDisplayedMnemonic('h');
        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel5.setLabelFor(hourSpinner);
        jLabel5.setText("hours");
        TimePickerPanel1.add(jLabel5);

        jLabel6.setDisplayedMnemonic('n');
        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel6.setLabelFor(minuteSpinner);
        jLabel6.setText("minutes");
        TimePickerPanel1.add(jLabel6);

        jLabel7.setDisplayedMnemonic('e');
        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel7.setLabelFor(secondSpinner);
        jLabel7.setText("seconds");
        TimePickerPanel1.add(jLabel7);

        HourSelectorSpinner.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        HourSelectorSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        HourSelectorSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                HourSelectorSpinnerStateChanged(evt);
            }
        });
        TimePickerPanel1.add(HourSelectorSpinner);

        MinuteSelectorSpinner.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        MinuteSelectorSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        MinuteSelectorSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MinuteSelectorSpinnerStateChanged(evt);
            }
        });
        TimePickerPanel1.add(MinuteSelectorSpinner);

        SecondSelectorSpinner.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        SecondSelectorSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        SecondSelectorSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SecondSelectorSpinnerStateChanged(evt);
            }
        });
        TimePickerPanel1.add(SecondSelectorSpinner);

        javax.swing.GroupLayout AlarmPanelLayout = new javax.swing.GroupLayout(AlarmPanel);
        AlarmPanel.setLayout(AlarmPanelLayout);
        AlarmPanelLayout.setHorizontalGroup(
            AlarmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlarmPanelLayout.createSequentialGroup()
                .addComponent(VolumePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlarmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlarmPanelLayout.createSequentialGroup()
                        .addGroup(AlarmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CurrentTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(AlarmPanelLayout.createSequentialGroup()
                        .addComponent(TimePickerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))))
        );
        AlarmPanelLayout.setVerticalGroup(
            AlarmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VolumePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AlarmPanelLayout.createSequentialGroup()
                .addComponent(CurrentTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimePickerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Alarm", AlarmPanel);

        volumeLabel2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        volumeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volumeLabel2.setLabelFor(volumeSlider);
        volumeLabel2.setText("Volume");
        volumeLabel2.setToolTipText("");
        volumeLabel2.setAlignmentX(0.5F);

        volumeSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSlider2StateChanged(evt);
            }
        });

        muteCheckbox2.setMnemonic('m');
        muteCheckbox2.setText("Mute");
        muteCheckbox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        muteCheckbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muteCheckbox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VolumePanel2Layout = new javax.swing.GroupLayout(VolumePanel2);
        VolumePanel2.setLayout(VolumePanel2Layout);
        VolumePanel2Layout.setHorizontalGroup(
            VolumePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolumePanel2Layout.createSequentialGroup()
                .addGroup(VolumePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volumeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(VolumePanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(VolumePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(volumeSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(muteCheckbox2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                .addContainerGap())
        );
        VolumePanel2Layout.setVerticalGroup(
            VolumePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolumePanel2Layout.createSequentialGroup()
                .addComponent(volumeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(muteCheckbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CurrentTimeLabel1.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        CurrentTimeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CurrentTimeLabel1.setText("00:00:00");
        CurrentTimeLabel1.setToolTipText("");

        startStopButton2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        startStopButton2.setMnemonic('s');
        startStopButton2.setText("Start/Stop");
        startStopButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStopButton2ActionPerformed(evt);
            }
        });

        resetButton2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        resetButton2.setMnemonic('r');
        resetButton2.setText("Reset");
        resetButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton2ActionPerformed(evt);
            }
        });

        LapButton.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        LapButton.setMnemonic('l');
        LapButton.setText("Lap");
        LapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanel2Layout = new javax.swing.GroupLayout(ButtonPanel2);
        ButtonPanel2.setLayout(ButtonPanel2Layout);
        ButtonPanel2Layout.setHorizontalGroup(
            ButtonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(startStopButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        ButtonPanel2Layout.setVerticalGroup(
            ButtonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ButtonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startStopButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        LapPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        LapPane.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "Laps", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 14))); // NOI18N

        javax.swing.GroupLayout StopwatchPanelLayout = new javax.swing.GroupLayout(StopwatchPanel);
        StopwatchPanel.setLayout(StopwatchPanelLayout);
        StopwatchPanelLayout.setHorizontalGroup(
            StopwatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StopwatchPanelLayout.createSequentialGroup()
                .addComponent(VolumePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StopwatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CurrentTimeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, Short.MAX_VALUE)
                    .addComponent(LapPane))
                .addContainerGap())
        );
        StopwatchPanelLayout.setVerticalGroup(
            StopwatchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VolumePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(StopwatchPanelLayout.createSequentialGroup()
                .addComponent(CurrentTimeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LapPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Stopwatch", StopwatchPanel);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        quitMenuItem.setMnemonic('q');
        quitMenuItem.setText("Quit");
        quitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(quitMenuItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuItemActionPerformed
        alarm.closeClip();
        beep.closeClip();
        System.exit(0);
    }//GEN-LAST:event_quitMenuItemActionPerformed

    private void LapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LapButtonActionPerformed

    private void resetButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButton2ActionPerformed

    private void startStopButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStopButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startStopButton2ActionPerformed

    private void muteCheckbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muteCheckbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muteCheckbox2ActionPerformed

    private void volumeSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSlider2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeSlider2StateChanged

    private void SecondSelectorSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SecondSelectorSpinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_SecondSelectorSpinnerStateChanged

    private void MinuteSelectorSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MinuteSelectorSpinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_MinuteSelectorSpinnerStateChanged

    private void HourSelectorSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_HourSelectorSpinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_HourSelectorSpinnerStateChanged

    private void resetButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButton1ActionPerformed

    private void startStopButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStopButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startStopButton1ActionPerformed

    private void muteCheckbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muteCheckbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muteCheckbox1ActionPerformed

    private void volumeSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSlider1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeSlider1StateChanged

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        if (timer != null)
        timer.cancel();
        if (timeLabelFlashTimer != null) {
            timeLabelFlashTimer.cancel();
            timeLabelFlashTimer = null;
        }
        timerIsRunning = false;
        time.reset();
        targetTime.reset();
        timeLabel.setText(time.toString());
        timeLabel.setForeground(timeLabelFg);
        hourSpinner.setValue(0);
        minuteSpinner.setValue(0);
        secondSpinner.setValue(0);
        millisecondSpinner.setValue(0);
        setSpinnersEnabled(true);
        alarm.stopAndRewind();
        enableIntervalIfTargetTimeIsSet();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void startStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStopButtonActionPerformed
        if (!timerIsRunning) {
            timerIsRunning = true;
            boolean isIntervalSelected = intervalCheckbox.isSelected();
            boolean isTargetTimeSet = isTargetTimeSet();
            intervalCheckbox.setEnabled(false);
            setSpinnersEnabled(false);

            timer = new Timer();
            timer.scheduleAtFixedRate(new TimerTask() {
                @Override
                public void run() {
                    /* Everything using Swing components, must be done from
                    * its event dispatching thread. */
                    SwingUtilities.invokeLater(() -> {
                        if (isTargetTimeSet &&
                            !isIntervalSelected &&
                            TimeUnits.timeUnitsAreEqual(time, targetTime)) {
                            timer.cancel();
                            alarm.play();
                            timeLabelFlashTimer = flashTime(timeLabelFlashTimer);

                            intervalCheckbox.setEnabled(true);
                            setSpinnersEnabled(true);
                        }
                        else if (timerIsRunning) {
                            time.advance();
                            timeLabel.setText(time.toString());
                        }

                        if (isIntervalSelected &&
                            targetTime.timeInMilliseconds() != 0 &&
                            time.mod(targetTime) == 0) {
                            beep.play();
                        }
                    });
                }
            }, 1, 1);
        }
        else {
            timer.cancel();
            if (timeLabelFlashTimer != null) {
                timeLabelFlashTimer.cancel();
                timeLabelFlashTimer = null;
            }
            timerIsRunning = false;
            alarm.stopAndRewind();

            setSpinnersEnabled(true);
            enableIntervalIfTargetTimeIsSet();
            timeLabel.setForeground(timeLabelFg);
        }
    }//GEN-LAST:event_startStopButtonActionPerformed

    private void muteCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muteCheckboxActionPerformed
        if (muteCheckbox.isSelected()) {
            alarm.mute(true);
            beep.mute(true);
        }
        else {
            alarm.mute(false);
            beep.mute(false);
        }
    }//GEN-LAST:event_muteCheckboxActionPerformed

    private void volumeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSliderStateChanged
        int volume = volumeSlider.getValue();
        beep.setVolume(volume, getSlideRange(volumeSlider));
        alarm.setVolume(volume, getSlideRange(volumeSlider));

        if (muteCheckbox.isSelected()) {
            muteCheckbox.setSelected(false);
            beep.mute(false);
            alarm.mute(false);
        }
    }//GEN-LAST:event_volumeSliderStateChanged

    private void secondSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_secondSpinnerStateChanged
        targetTime.setSeconds((Integer) secondSpinner.getValue());
        enableIntervalIfTargetTimeIsSet();
    }//GEN-LAST:event_secondSpinnerStateChanged

    private void hourSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hourSpinnerStateChanged
        targetTime.setHours((Integer) hourSpinner.getValue());
        enableIntervalIfTargetTimeIsSet();
    }//GEN-LAST:event_hourSpinnerStateChanged

    private void minuteSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_minuteSpinnerStateChanged
        targetTime.setMinutes((Integer) minuteSpinner.getValue());
        enableIntervalIfTargetTimeIsSet();
    }//GEN-LAST:event_minuteSpinnerStateChanged

    private void millisecondSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_millisecondSpinnerStateChanged
        targetTime.setMilliseconds((Integer) millisecondSpinner.getValue());
        enableIntervalIfTargetTimeIsSet();
    }//GEN-LAST:event_millisecondSpinnerStateChanged

    private void intervalCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intervalCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intervalCheckboxActionPerformed

    private Timer flashTime(Timer tOld) {
        if (tOld != null)
            tOld.cancel();

        Color bg = timeLabel.getBackground();
        Timer t = new Timer();
        t.scheduleAtFixedRate(new TimerTask() {
            private boolean b = true;
            @Override
            public void run() {
                Color c = b ? bg : timeLabelFg;
                b = !b;
                SwingUtilities.invokeLater(() -> {
                    timeLabel.setForeground(c);
                });
            }
        }, 0, 500);

        return t;
    }

    /** Check is target time set. It's set if at least some of the spinners
     * is non-zero.
     * @return False if all the spinners have zero value, true otherwise.
     */
    private boolean isTargetTimeSet() {
        return ((Integer) hourSpinner.getValue()) != 0 ||
               ((Integer) minuteSpinner.getValue()) != 0 ||
               ((Integer) secondSpinner.getValue()) != 0 ||
               ((Integer) millisecondSpinner.getValue()) != 0;
    }

    /** Enable or disable all the spinners.
     * @param b Enable or disable spinners.
     */
    private void setSpinnersEnabled(boolean b) {
        hourSpinner.setEnabled(b);
        minuteSpinner.setEnabled(b);
        secondSpinner.setEnabled(b);
        millisecondSpinner.setEnabled(b);
    }

    /** Interval checkbox can be enabled only when target time is set.
     * Enable interval checkbox when target time is set. Otherwise, disable
     * checkbox and set it unselected.
     */
    private void enableIntervalIfTargetTimeIsSet() {
        if (isTargetTimeSet())
            intervalCheckbox.setEnabled(true);
        else {
            intervalCheckbox.setEnabled(false);
            intervalCheckbox.setSelected(false);
        }
    }
    
    /** Get range of the slider. |slider.max - slider.min|.
     * @param slider
     * @return The range of the slider.
     */
    private static int getSlideRange(JSlider slider) {
        return Math.abs(slider.getMaximum() - slider.getMinimum());
    }

    /** Get middle value of a slider component.
     * @param slider
     * @return
     */
    private static int getSliderMiddle(JSlider slider) {
        return (slider.getMaximum() - slider.getMinimum()) / 2;
    }

    /** Calculate such a point for a window, that when positioned on that
     * point, the window will be in the center of the screen.
     * @return Point for centering a window.
     */
    private static Point getScreenCenterForWindow(Window c) {
        double height = c.getBounds().getHeight();
        double width  = c.getBounds().getWidth();
        Point center  = GraphicsEnvironment.getLocalGraphicsEnvironment().
            getCenterPoint();
        center.setLocation(center.getX() - width / 2,
                           center.getY() - height / 2);
        
        return center;
    }

    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlarmPanel;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel ButtonPanel1;
    private javax.swing.JPanel ButtonPanel2;
    private javax.swing.JLabel CurrentTimeLabel;
    private javax.swing.JLabel CurrentTimeLabel1;
    private javax.swing.JSpinner HourSelectorSpinner;
    private javax.swing.JButton LapButton;
    private javax.swing.JScrollPane LapPane;
    private javax.swing.JSpinner MinuteSelectorSpinner;
    private javax.swing.JSpinner SecondSelectorSpinner;
    private javax.swing.JPanel StopwatchPanel;
    private javax.swing.JPanel TimePickerPanel;
    private javax.swing.JPanel TimePickerPanel1;
    private javax.swing.JPanel TimerPanel;
    private javax.swing.JPanel VolumePanel;
    private javax.swing.JPanel VolumePanel1;
    private javax.swing.JPanel VolumePanel2;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JSpinner hourSpinner;
    private javax.swing.JCheckBox intervalCheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner millisecondSpinner;
    private javax.swing.JSpinner minuteSpinner;
    private javax.swing.JCheckBox muteCheckbox;
    private javax.swing.JCheckBox muteCheckbox1;
    private javax.swing.JCheckBox muteCheckbox2;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resetButton1;
    private javax.swing.JButton resetButton2;
    private javax.swing.JSpinner secondSpinner;
    private javax.swing.JButton startStopButton;
    private javax.swing.JButton startStopButton1;
    private javax.swing.JButton startStopButton2;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JLabel volumeLabel1;
    private javax.swing.JLabel volumeLabel2;
    private javax.swing.JSlider volumeSlider;
    private javax.swing.JSlider volumeSlider1;
    private javax.swing.JSlider volumeSlider2;
    // End of variables declaration//GEN-END:variables
}
