package fluks.timerng;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 */
public class StopwatchTab extends JPanel {
    private Timer timer;
    private volatile TimeUnits time;
    private static final long NOT_RUNNING = -1;
    private long lastLapInMS = NOT_RUNNING;

    /**
     */
    public StopwatchTab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new JPanel();
        timeLabel = new JLabel();
        jPanel3 = new JPanel();
        scrollPane = new JScrollPane();
        lapsPanel = new JPanel();
        jPanel4 = new JPanel();
        startStopButton = new JButton();
        lapButton = new JButton();
        resetButton = new JButton();

        setBorder(BorderFactory.createEmptyBorder(20, 1, 20, 1));
        setLayout(new BoxLayout(this, BoxLayout.X_AXIS));

        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

        timeLabel.setFont(new Font("Dialog", 1, 70)); // NOI18N
        timeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        timeLabel.setText("00:00:00:000");
        timeLabel.setAlignmentX(0.5F);
        timeLabel.setMaximumSize(new Dimension(39999, 420));
        timeLabel.setPreferredSize(new Dimension(42000, 96));
        jPanel2.add(timeLabel);

        jPanel3.setMinimumSize(new Dimension(67, 32));
        jPanel3.setPreferredSize(new Dimension(420, 44));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new CardLayout());

        scrollPane.setViewportBorder(BorderFactory.createTitledBorder("Laps"));

        lapsPanel.setLayout(new BoxLayout(lapsPanel, BoxLayout.PAGE_AXIS));
        scrollPane.setViewportView(lapsPanel);

        jPanel3.add(scrollPane, "card2");

        jPanel2.add(jPanel3);

        startStopButton.setMnemonic('s');
        startStopButton.setText("Start / Stop");
        startStopButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                startStopButtonActionPerformed(evt);
            }
        });
        jPanel4.add(startStopButton);

        lapButton.setMnemonic('l');
        lapButton.setText("Lap");
        lapButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                lapButtonActionPerformed(evt);
            }
        });
        jPanel4.add(lapButton);

        resetButton.setMnemonic('r');
        resetButton.setText("Reset");
        resetButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel4.add(resetButton);

        jPanel2.add(jPanel4);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void lapButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_lapButtonActionPerformed
        if (timer != null) {
            var now = time.timeInMilliseconds();
            long lap;
            if (lastLapInMS != NOT_RUNNING) {
                lap = now - lastLapInMS;
            }
            else {
                lap = now;
            }
            lastLapInMS = now;
            var label = new JLabel();
            label.setText((new TimeUnits(lap)).toString());
            lapsPanel.add(label);
            lapsPanel.revalidate();
            lapsPanel.repaint();

            var bar = scrollPane.getVerticalScrollBar();
            SwingUtilities.invokeLater(() -> {
                bar.setValue(bar.getMaximum());
            });
        }
    }//GEN-LAST:event_lapButtonActionPerformed

    private void resetButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        if (timer != null) {
            timer.cancel();
            timer = null;
            time = null;
            lastLapInMS = NOT_RUNNING;
        }
        timeLabel.setText("00:00:00:000");
        lapsPanel.removeAll();
        lapsPanel.revalidate();
        lapsPanel.repaint();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void startStopButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_startStopButtonActionPerformed
        if (timer == null) {
            timer = new Timer();
            time = new TimeUnits();
            timer.scheduleAtFixedRate(new TimerTask() {
                @Override
                public void run() {
                    time.advance();
                    SwingUtilities.invokeLater(() -> {
                        timeLabel.setText(time.toString());
                    });
                }
            }, 1, 1);
        }
        else {
            lapButtonActionPerformed(null);

            timer.cancel();
            timer = null;
            time = new TimeUnits();
            lastLapInMS = NOT_RUNNING;
        }
    }//GEN-LAST:event_startStopButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JButton lapButton;
    private JPanel lapsPanel;
    private JButton resetButton;
    private JScrollPane scrollPane;
    private JButton startStopButton;
    private JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
