package fluks.timerng;

import fluks.swing.utils.SwingUtils;
import fluks.timerng.sound.AbstractClipWrapper;
import fluks.timerng.sound.NoSound;
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.MalformedURLException;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class TimerTab extends JPanel {
    private boolean interval = false;
    private boolean muted = false;
    private static final String START_TIME = "00:00:00:000";
    private TimeUnits time = new TimeUnits();
    private TimeUnits target = new TimeUnits();
    private Timer timer;
    private Timer flashTimeLabelTimer;
    private final Color timeLabelFg;
    private boolean timerIsRunning = false;
    private final AbstractClipWrapper beep;
    private final AbstractClipWrapper alarm;
    private final int volumeRange;

    public TimerTab() {
        initComponents();
        timeLabelFg = timeLabel.getForeground();
        var sound = Global.getSoundInstance();
        beep = sound.getBeep();
        alarm = sound.getAlarm();
        volumeRange = SwingUtils.getSliderRange(volumeSlider);
        if ((beep instanceof NoSound) && (alarm instanceof NoSound)) {
            volumeSlider.setEnabled(false);
            muteCheckBox.setEnabled(false);
        }
        else {
            var middle = SwingUtils.getSliderMiddle(volumeSlider);
            alarm.setVolume(middle, volumeRange);
            beep.setVolume(middle, volumeRange);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        jPanel1 = new JPanel();
        volumeLabel = new JLabel();
        volumeSlider = new JSlider();
        muteCheckBox = new JCheckBox();
        jPanel2 = new JPanel();
        timeLabel = new JLabel();
        jPanel3 = new JPanel();
        hoursLabel = new JLabel();
        hoursSpinner = new JSpinner();
        minutesLabel = new JLabel();
        minutesSpinner = new JSpinner();
        secondsLabel = new JLabel();
        secondsSpinner = new JSpinner();
        millisecondsLabel = new JLabel();
        millisecondsSpinner = new JSpinner();
        intervalCheckBox = new JCheckBox();
        jPanel4 = new JPanel();
        startStopButton = new JButton();
        resetButton = new JButton();

        setBorder(BorderFactory.createEmptyBorder(20, 1, 20, 1));
        setLayout(new BoxLayout(this, BoxLayout.X_AXIS));

        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));

        volumeLabel.setDisplayedMnemonic('v');
        volumeLabel.setLabelFor(volumeSlider);
        volumeLabel.setText("Volume");
        volumeLabel.setBorder(BorderFactory.createEmptyBorder(1, 1, 20, 1));
        jPanel1.add(volumeLabel);

        volumeSlider.setOrientation(JSlider.VERTICAL);
        volumeSlider.setMaximumSize(new Dimension(32767, 32767));
        volumeSlider.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                volumeSliderStateChanged(evt);
            }
        });
        jPanel1.add(volumeSlider);

        muteCheckBox.setMnemonic('u');
        muteCheckBox.setText("Mute");
        muteCheckBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                muteCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(muteCheckBox);

        add(jPanel1);

        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

        timeLabel.setFont(new Font("Dialog", 1, 70)); // NOI18N
        timeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        timeLabel.setText("00:00:00:000");
        timeLabel.setAlignmentX(0.5F);
        timeLabel.setMaximumSize(new Dimension(39999, 420));
        timeLabel.setPreferredSize(new Dimension(42000, 96));
        jPanel2.add(timeLabel);

        jPanel3.setMinimumSize(new Dimension(67, 32));
        jPanel3.setPreferredSize(new Dimension(420, 44));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new GridBagLayout());

        hoursLabel.setDisplayedMnemonic('h');
        hoursLabel.setLabelFor(hoursSpinner);
        hoursLabel.setText("Hours");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        jPanel3.add(hoursLabel, gridBagConstraints);

        hoursSpinner.setModel(new SpinnerNumberModel(0, 0, null, 1));
        hoursSpinner.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                hoursSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        jPanel3.add(hoursSpinner, gridBagConstraints);

        minutesLabel.setDisplayedMnemonic('m');
        minutesLabel.setLabelFor(minutesSpinner);
        minutesLabel.setText("Minutes");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        jPanel3.add(minutesLabel, gridBagConstraints);

        minutesSpinner.setModel(new SpinnerNumberModel(0, 0, 59, 1));
        minutesSpinner.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                minutesSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        jPanel3.add(minutesSpinner, gridBagConstraints);

        secondsLabel.setDisplayedMnemonic('e');
        secondsLabel.setLabelFor(secondsSpinner);
        secondsLabel.setText("Seconds");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        jPanel3.add(secondsLabel, gridBagConstraints);

        secondsSpinner.setModel(new SpinnerNumberModel(0, 0, 59, 1));
        secondsSpinner.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                secondsSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        jPanel3.add(secondsSpinner, gridBagConstraints);

        millisecondsLabel.setDisplayedMnemonic('i');
        millisecondsLabel.setLabelFor(millisecondsSpinner);
        millisecondsLabel.setText("Milliseconds");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        jPanel3.add(millisecondsLabel, gridBagConstraints);

        millisecondsSpinner.setModel(new SpinnerNumberModel(0, 0, 999, 1));
        millisecondsSpinner.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                millisecondsSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        jPanel3.add(millisecondsSpinner, gridBagConstraints);

        intervalCheckBox.setMnemonic('i');
        intervalCheckBox.setText("Interval");
        intervalCheckBox.setEnabled(false);
        intervalCheckBox.setHorizontalAlignment(SwingConstants.LEFT);
        intervalCheckBox.setMaximumSize(new Dimension(99999, 29));
        intervalCheckBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                intervalCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel3.add(intervalCheckBox, gridBagConstraints);

        jPanel2.add(jPanel3);

        startStopButton.setMnemonic('s');
        startStopButton.setText("Start / Stop");
        startStopButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                startStopButtonActionPerformed(evt);
            }
        });
        jPanel4.add(startStopButton);

        resetButton.setMnemonic('r');
        resetButton.setText("Reset");
        resetButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel4.add(resetButton);

        jPanel2.add(jPanel4);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void intervalCheckBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_intervalCheckBoxActionPerformed
        interval = intervalCheckBox.isSelected();
    }//GEN-LAST:event_intervalCheckBoxActionPerformed

    private void resetButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        muteCheckBox.setSelected(false);
        muted = false;
        intervalCheckBox.setSelected(false);
        interval = false;
        hoursSpinner.setValue(0);
        minutesSpinner.setValue(0);
        secondsSpinner.setValue(0);
        millisecondsSpinner.setValue(0);
        timeLabel.setText(START_TIME);

        time = new TimeUnits();
        target = new TimeUnits();
        timerIsRunning = false;
        if (timer != null) {
            timer.cancel();
            timer = null;
        }
        if (flashTimeLabelTimer != null) {
            flashTimeLabelTimer.cancel();
            flashTimeLabelTimer = null;
            timeLabel.setForeground(timeLabelFg);
        }
        alarm.stopAndRewind();
        alarm.mute(false);
        beep.mute(false);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void muteCheckBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_muteCheckBoxActionPerformed
        muted = muteCheckBox.isSelected();
        alarm.mute(muted);
        beep.mute(muted);

    }//GEN-LAST:event_muteCheckBoxActionPerformed

    private void startStopButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_startStopButtonActionPerformed
        if (target.timeInMilliseconds() == 0) {
            return;
        }

        if (timerIsRunning) {
            timer.cancel();
            timerIsRunning = false;
        }
        else {
            timerIsRunning = true;
            timer = new Timer();
            timer.scheduleAtFixedRate(new TimerTask() {
                @Override
                public void run() {
                    time.advance();
                    SwingUtilities.invokeLater(() -> {
                        timeLabel.setText(time.toString());
                    });
                    if (interval && time.mod(target) == 0 && !muted) {
                        beep.play();
                    }
                    else if (TimeUnits.timeUnitsAreEqual(time, target)) {
                        alarm.play();
                        SwingUtilities.invokeLater(() -> {
                            try {
                                SwingUtils.showDesktopNotification(
                                        "Timer finished",
                                        "Timer you set to " + target.toString() + " is finished.",
                                        Global.PROGRAM_NAME,
                                        null,
                                        5000);
                            } catch (MalformedURLException | AWTException ex) {
                            }
                        });
                        timer.cancel();
                        timerIsRunning = false;
                        flashTimeLabelTimer = SwingUtils.blinkComponent(timeLabel, 500);
                    }
                }
            }, 1, 1);
        }
    }//GEN-LAST:event_startStopButtonActionPerformed

    private void volumeSliderStateChanged(ChangeEvent evt) {//GEN-FIRST:event_volumeSliderStateChanged
        var volume = volumeSlider.getValue();
        beep.setVolume(volume, volumeRange);
        alarm.setVolume(volume, volumeRange);
    }//GEN-LAST:event_volumeSliderStateChanged

    private void hoursSpinnerStateChanged(ChangeEvent evt) {//GEN-FIRST:event_hoursSpinnerStateChanged
        target.setHours((int) hoursSpinner.getValue());
        intervalCheckBox.setEnabled(target.timeInMilliseconds() > 0);
    }//GEN-LAST:event_hoursSpinnerStateChanged

    private void minutesSpinnerStateChanged(ChangeEvent evt) {//GEN-FIRST:event_minutesSpinnerStateChanged
        target.setMinutes((int) minutesSpinner.getValue());
        intervalCheckBox.setEnabled(target.timeInMilliseconds() > 0);
    }//GEN-LAST:event_minutesSpinnerStateChanged

    private void secondsSpinnerStateChanged(ChangeEvent evt) {//GEN-FIRST:event_secondsSpinnerStateChanged
        target.setSeconds((int) secondsSpinner.getValue());
        intervalCheckBox.setEnabled(target.timeInMilliseconds() > 0);
    }//GEN-LAST:event_secondsSpinnerStateChanged

    private void millisecondsSpinnerStateChanged(ChangeEvent evt) {//GEN-FIRST:event_millisecondsSpinnerStateChanged
        target.setMilliseconds((int) millisecondsSpinner.getValue());
        intervalCheckBox.setEnabled(target.timeInMilliseconds() > 0);
    }//GEN-LAST:event_millisecondsSpinnerStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel hoursLabel;
    private JSpinner hoursSpinner;
    private JCheckBox intervalCheckBox;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JLabel millisecondsLabel;
    private JSpinner millisecondsSpinner;
    private JLabel minutesLabel;
    private JSpinner minutesSpinner;
    private JCheckBox muteCheckBox;
    private JButton resetButton;
    private JLabel secondsLabel;
    private JSpinner secondsSpinner;
    private JButton startStopButton;
    private JLabel timeLabel;
    private JLabel volumeLabel;
    private JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables
}
