/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fluks.timerng;

/**
 *
 * @author jukka
 */
public class TimezonesTab extends javax.swing.JPanel {

    /**
     * Creates new form TimerTab
     */
    public TimezonesTab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        timezonesComboBox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        timeZonesScrollPane = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        resetButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.add(timezonesComboBox);

        addButton.setMnemonic('a');
        addButton.setText("Add");
        jPanel5.add(addButton);

        jPanel2.add(jPanel5);

        jPanel3.setMinimumSize(new java.awt.Dimension(67, 32));
        jPanel3.setPreferredSize(new java.awt.Dimension(420, 44));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.CardLayout());
        jPanel3.add(timeZonesScrollPane, "card2");

        jPanel2.add(jPanel3);

        resetButton.setMnemonic('r');
        resetButton.setText("Reset");
        resetButton.setToolTipText("");
        jPanel4.add(resetButton);

        jPanel2.add(jPanel4);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton resetButton;
    private javax.swing.JScrollPane timeZonesScrollPane;
    private javax.swing.JComboBox<String> timezonesComboBox;
    // End of variables declaration//GEN-END:variables
}
