package fluks.timerng;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;
import java.util.TreeSet;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class TimezonesTab extends javax.swing.JPanel {
    private Map<String, Timer> timers;

    public TimezonesTab() {
        initComponents();
        addTimeZones();
        timers = new HashMap<>();
    }

    private void addTimeZones() {
        var ids = new TreeSet<String>(ZoneId.getAvailableZoneIds());
        for (var id : ids) {
            var tz = ZoneId.of(id);
            timezonesComboBox.addItem(new TZObject(tz));
        } 
    }

    private final class TZObject {
        private ZoneId id;

        public TZObject(ZoneId id) {
            this.id = id;
        }

        public ZoneId getId() {
            return id;
        }

        @Override
        public String toString() {
            var now = ZonedDateTime.now(id);
            return now.getOffset() + " " + id;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        timezonesComboBox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        timeZonesScrollPane = new javax.swing.JScrollPane();
        timezonesPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        resetButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.add(timezonesComboBox);

        addButton.setMnemonic('a');
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel5.add(addButton);

        jPanel2.add(jPanel5);

        jPanel3.setMinimumSize(new java.awt.Dimension(67, 32));
        jPanel3.setPreferredSize(new java.awt.Dimension(420, 44));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.CardLayout());

        timezonesPanel.setLayout(new javax.swing.BoxLayout(timezonesPanel, javax.swing.BoxLayout.PAGE_AXIS));
        timeZonesScrollPane.setViewportView(timezonesPanel);

        jPanel3.add(timeZonesScrollPane, "card2");

        jPanel2.add(jPanel3);

        resetButton.setMnemonic('r');
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel4.add(resetButton);

        jPanel2.add(jPanel4);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        var tz = (TZObject) timezonesComboBox.getSelectedItem();
        timezonesPanel.add(new TimeZonePanel(tz));
        timezonesPanel.revalidate();

        var bar = timeZonesScrollPane.getVerticalScrollBar();
        SwingUtilities.invokeLater(() -> {
            bar.setValue(bar.getMaximum());
        });
    }//GEN-LAST:event_addActionPerformed

    private void resetButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        timers.values().stream().forEach((t) -> {
            t.cancel();
        });
        timers.clear();
        timezonesPanel.removeAll();
        timezonesPanel.repaint();
    }//GEN-LAST:event_resetButtonActionPerformed

    private final class TimeZonePanel extends JPanel {
        private final JLabel timeLabel;
        private final JLabel tzLabel;
        private final JButton removeButton;
        private final TZObject tz;

        public TimeZonePanel(TZObject tz) {
            this.tz = tz;

            setAlignmentX(0.0F);
            setLayout(new BoxLayout(this, BoxLayout.LINE_AXIS));

            tzLabel = new JLabel();
            tzLabel.setText(tz.toString());
            add(tzLabel);

            var filler2 = new Box.Filler(new Dimension(20, 0), new Dimension(20, 0), new Dimension(20, 0));
            add(filler2);

            timeLabel = new JLabel();
            timeLabel.setText("00:00:00");
            add(timeLabel);

            var filler1 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(10000, 0));
            add(filler1);

            removeButton = new JButton();
            removeButton.setIcon(new ImageIcon(getClass().getResource("/resources/remove.png"))); // NOI18N
            removeButton.setToolTipText("Remove");
            removeButton.setBorderPainted(false);
            removeButton.setContentAreaFilled(false);
            removeButton.setFocusPainted(false);
            removeButton.addActionListener(this::removeButtonActionPerformed);
            add(removeButton);

            timers.put(tz.toString(), addTimer());
        }

        private Timer addTimer() {
            var timer = new Timer();
            timer.scheduleAtFixedRate(new TimerTask() {
                ZonedDateTime now = ZonedDateTime.now(tz.getId());
                private TimeUnits time = new TimeUnits(now.getHour(), now.getMinute(), now.getSecond(), 0);
                {
                    time.setFormat("%02d%c%02d%c%02d");
                }

                @Override
                public void run() {
                    SwingUtilities.invokeLater(() -> {
                        timeLabel.setText(time.toString());
                    });
                    time.advanceSecond();
                }
            }, 0, 1000);

            return timer;
        }

        private void removeButtonActionPerformed(ActionEvent evt) {
            var parent = getParent();
            if (parent != null) {
                timers.remove(tz.toString());
                
                parent.remove(this);
                parent.revalidate();
                parent.repaint();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton resetButton;
    private javax.swing.JScrollPane timeZonesScrollPane;
    private javax.swing.JComboBox<TZObject> timezonesComboBox;
    private javax.swing.JPanel timezonesPanel;
    // End of variables declaration//GEN-END:variables
}
